; --- AFE Firmware T6 ------------------------------------------------------
; Generic congis for T6

[common-t6]
lib_deps                  = https://github.com/tschaban/Adafruit_Sensor.git#afe/1.0
                            https://github.com/tschaban/Adafruit_BusIO.git#afe/1.0
                            https://github.com/tschaban/Bosch-BME68x-Library.git
                            https://github.com/tschaban/Bosch-BSEC2-Library.git
                            ;https://github.com/tschaban/BSEC-Arduino-library.git#afe/1.0 (MUST BE DOWNLOADED LOCALLY)
                            https://github.com/tschaban/Adafruit-BMP085-Library.git#afe/1.1
                            https://github.com/tschaban/Adafruit_BME280_Library.git#afe/1.0                            
                            https://github.com/tschaban/BH1750.git#afe/3.3
                            ;https://github.com/tschaban/Adafruit_BME680.git#afe/1.0
                            https://github.com/tschaban/Arduino-Temperature-Control-Library.git#afe/1.2
                            https://github.com/tschaban/DHTesp.git#afe/1.1
                            https://github.com/tschaban/Adafruit_TSL2561.git#afe/1.0
                            https://github.com/PaulStoffregen/OneWire
                            https://github.com/tschaban/SparkFun_FS3000_Arduino_Library.git
                            SPI
                            ;Wire
                            EspSoftwareSerial

build_flags                = -DT6_CONFIG
                             -Llib-external/Bosch-BSEC2-Library/src/esp8266 -lalgobsec ; testing BSEC v2
                            ;-Llib-external/BSEC-Arduino-library/src/esp8266 -lalgobsec

[AFE_T6_ESP82xx_Production] 
build_flags               = ${core82xx.build_flags}
                            ${production.build_flags}
                            ${common-t6.build_flags}                            
lib_ignore                = ${core82xx.build_flags}
                            ${production.lib_ignore}
                         

[AFE_T6_ESP82xx_Development]
build_flags               = ${core82xx.build_flags}
                            ${development.build_flags}
                            ${common-t6.build_flags}
lib_ignore                = ${core82xx.build_flags}
                            ${development.lib_ignore}


[AFE_T6_ESP32_Production]
build_flags               = ${core32.build_flags}
                            ${production.build_flags}
                            ${common-t6.build_flags}
lib_ignore                = ${core32.build_flags}
                            ${production.lib_ignore}

[AFE_T6_ESP32_Development]
build_flags               = ${core32.build_flags}
                            ${development.build_flags}
                            ${common-t6.build_flags}
lib_ignore                = ${core32.build_flags}
                            ${development.lib_ignore}


; ------------------------------------------------------------------
; Boards
; ESP8266 4M Formated to 2M

[env:AFE_T6_8266_4m]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}

[env:AFE_T6_8266_4m-domoticz]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_8266_4m-ha]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T6_8266_4m-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}

[env:AFE_T6_8266_4m-domoticz-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_8266_4m-ha-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


; ESP8266 1Mb

[env:AFE_T6_8266_1m]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}


[env:AFE_T6_8266_1m-domoticz]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_8266_1m-ha]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


[env:AFE_T6_8266_1m-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}


[env:AFE_T6_8266_1m-domoticz-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_8266_1m-ha-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

; AFE T6 custmized versions

; E1 - ESP8266 4MB
; 12 x DS18B20
; 2 x BME
; 1 x Swich
; 1 x LED

[env:AFE_T6_8266_4m-e1]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_T6_CUSTOM_E1

[env:AFE_T6_8266_4m-domoticz-e1]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_T6_CUSTOM_E1

[env:AFE_T6_8266_4m-ha-e1]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_T6_CUSTOM_E1

; E2 - ESP8266 4MB
; 2xBME 
; 8xDS18B20
[env:AFE_T6_8266_4m-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_T6_CUSTOM_E2

[env:AFE_T6_8266_4m-domoticz-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_T6_CUSTOM_E2

[env:AFE_T6_8266_4m-ha-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_T6_CUSTOM_E2




; --- AFE Firmware T6 ------------------------------------------------------


; ESP8266, 4MB iECSv2

[env:AFE_T6_8266_4m-iECSv20]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_DEVICE_iECS_WHEATER_STATION_20

[env:AFE_T6_8266_4m-domoticz-iECSv20]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_DEVICE_iECS_WHEATER_STATION_20

[env:AFE_T6_8266_4m-ha-iECSv20]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_DEVICE_iECS_WHEATER_STATION_20


; ESP8266, 4MB iECSv2.1

[env:AFE_T6_8266_4m-iECSv21]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_DEVICE_iECS_WHEATER_STATION_21

[env:AFE_T6_8266_4m-domoticz-iECSv21]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_DEVICE_iECS_WHEATER_STATION_21

[env:AFE_T6_8266_4m-ha-iECSv21]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_DEVICE_iECS_WHEATER_STATION_21


; ESP32 38Pins

[env:AFE_T6_esp32_4m_38P]
extends                   = esp32_4M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Production.build_flags}

[env:AFE_T6_esp32_4m_38P-development]
extends                   = esp32_4M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Development.build_flags}

[env:AFE_T6_esp32_4m_38P-domoticz]
extends                   = esp32_4M
lib_ignore                = ${AFE_T6_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_esp32_4m_38P-domoticz-development]
extends                   = esp32_4M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T6_esp32_4m_38P-ha]
extends                   = esp32_4M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Production.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T6_esp32_4m_38P-ha-development]
extends                   = esp32_4M
lib_deps                  = ${common-t6.lib_deps}
lib_ignore                = ${AFE_T6_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T6_ESP32_Development.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
