; --- AFE Firmware T1 ------------------------------------------------------
; Generic congis for T1

[common_t1]
lib_deps                  = https://github.com/tschaban/Arduino-Temperature-Control-Library.git#afe/1.2


[AFE_T1_ESP82xx_Production] 
build_flags               = ${ESP86xx_base.build_flags}
                            ${production.build_flags}
                            -DT1_CONFIG
lib_deps                  = ${ESP86xx_base.lib_deps}
                            ${common_t1.lib_deps}
lib_ignore                = ${ESP86xx_base.lib_ignore}
                            ${production.lib_ignore}
                         

[AFE_T1_ESP82xx_Development]
build_flags               = ${ESP86xx_base.build_flags}
                            ${development.build_flags}
                            -DT1_CONFIG
lib_deps                  = ${ESP86xx_base.lib_deps}
                            ${common_t1.lib_deps}                            
lib_ignore                = ${ESP86xx_base.lib_ignore}
                            ${development.lib_ignore}


[AFE_T1_ESP32_Production]
lib_deps                  = ${ESP32_base.lib_deps}
                            ${common_t1.lib_deps}     
build_flags               = ${ESP32_base.build_flags}
                            ${production.build_flags}
                            -DT1_CONFIG                       
lib_ignore                = ${ESP32_base.lib_ignore}
                            ${production.lib_ignore}

[AFE_T1_ESP32_Development]
build_flags               = ${ESP32_base.build_flags}
                            ${development.build_flags}
                            -DT1_CONFIG
lib_deps                  = ${ESP32_base.lib_deps}
                            ${common_t1.lib_deps}                              
lib_ignore                = ${ESP32_base.lib_ignore}
                            ${development.lib_ignore}


; ------------------------------------------------------------------
; Boards
; ESP8266 4M Formated to 2M

[env:AFE_T1_8266_4m]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}

[env:AFE_T1_8266_4m-domoticz]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_8266_4m-ha]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T1_8266_4m-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}

[env:AFE_T1_8266_4m-domoticz-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_8266_4m-ha-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


; ESP8266 1Mb

[env:AFE_T1_8266_1m]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}


[env:AFE_T1_8266_1m-domoticz]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_8266_1m-ha]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


[env:AFE_T1_8266_1m-development]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}


[env:AFE_T1_8266_1m-domoticz-development]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_8266_1m-ha-development]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Development.lib_ignore}build_flags
build_flags               = ${AFE_T1_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

; ESP8285

[env:AFE_T1_8285]
extends                   = esp8255_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}


[env:AFE_T1_8285-domoticz]
extends                   = esp8255_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED


[env:AFE_T1_8285-ha]
extends                   = esp8255_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED



; ESP32 38Pins

[env:AFE_T1_esp32_4m_38P]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Production.build_flags}

[env:AFE_T1_esp32_4m_38P-development]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Development.build_flags}

[env:AFE_T1_esp32_4m_38P-domoticz]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_esp32_4m_38P-domoticz-development]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T1_esp32_4m_38P-ha]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Production.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T1_esp32_4m_38P-ha-development]
extends                   = esp32_4M
lib_deps                  = ${AFE_T1_ESP32_Development.lib_deps}
lib_ignore                = ${AFE_T1_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T1_ESP32_Development.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


; AFE T1 custmized versions

; ESP8266 1mb: E1 - 30 DS18B20 + 1 LED + 1 Switch
[env:AFE_T1_8266_1m-e1]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_T1_CUSTOM_E1


[env:AFE_T1_8266_1m-domoticz-e1]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_T1_CUSTOM_E1

[env:AFE_T1_8266_1m-ha-e1]
extends                   = esp8266_1M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_T1_CUSTOM_E1


; ESP8266 1mb: E2 - 8xRelays, 8xSwitch, 8xLEDs, 8xDS18B20
[env:AFE_T1_8266_4m-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_T1_CUSTOM_E2

[env:AFE_T1_8266_4m-domoticz-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED
                            -DAFE_T1_CUSTOM_E2

[env:AFE_T1_8266_4m-ha-e2]
extends                   = esp8266_4MF2M
lib_deps                  = ${AFE_T1_ESP82xx_Production.lib_deps}
lib_ignore                = ${AFE_T1_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T1_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
                            -DAFE_T1_CUSTOM_E2


