; --- AFE Firmware T4 ------------------------------------------------------
; Generic congis for T4

[common-t4]
lib_deps                  = https://github.com/tschaban/Arduino-Temperature-Control-Library.git#afe/1.2
                            https://github.com/tschaban/Adafruit-MCP23017-Arduino-Library.git

[AFE_T4_ESP82xx_Production] 
build_flags               = ${core82xx.build_flags}
                            ${production.build_flags}
                            -DT4_CONFIG
lib_ignore                = ${core82xx.build_flags}
                            ${production.lib_ignore}
                         

[AFE_T4_ESP82xx_Development]
build_flags               = ${core82xx.build_flags}
                            ${development.build_flags}
                            -DT4_CONFIG
lib_ignore                = ${core82xx.build_flags}
                            ${development.lib_ignore}


[AFE_T4_ESP32_Production]
build_flags               = ${core32.build_flags}
                            ${production.build_flags}
                            -DT4_CONFIG
lib_ignore                = ${core32.build_flags}
                            ${production.lib_ignore}

[AFE_T4_ESP32_Development]
build_flags               = ${core32.build_flags}
                            ${development.build_flags}
                            -DT4_CONFIG
lib_ignore                = ${core32.build_flags}
                            ${development.lib_ignore}


; ------------------------------------------------------------------
; Boards
; ESP8266 4M Formated to 2M

[env:AFE_T4_8266_4m]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}

[env:AFE_T4_8266_4m-domoticz]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_8266_4m-ha]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T4_8266_4m-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}

[env:AFE_T4_8266_4m-domoticz-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_8266_4m-ha-development]
extends                   = esp8266_4MF2M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


; ESP8266 1Mb

[env:AFE_T4_8266_1m]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}


[env:AFE_T4_8266_1m-domoticz]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_8266_1m-ha]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED


[env:AFE_T4_8266_1m-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}


[env:AFE_T4_8266_1m-domoticz-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_8266_1m-ha-development]
extends                   = esp8266_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Development.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

; ESP8285

[env:AFE_T4_8285]
extends                   = esp8255_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}


[env:AFE_T4_8285-domoticz]
extends                   = esp8255_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED


[env:AFE_T4_8285-ha]
extends                   = esp8255_1M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP82xx_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP82xx_Production.build_flags}
                            -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED



; ESP32 38Pins

[env:AFE_T4_esp32_4m_38P]
extends                   = esp32_4M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Production.build_flags}

[env:AFE_T4_esp32_4m_38P-development]
extends                   = esp32_4M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Development.build_flags}

[env:AFE_T4_esp32_4m_38P-domoticz]
extends                   = esp32_4M
lib_ignore                = ${AFE_T4_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Production.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_esp32_4m_38P-domoticz-development]
extends                   = esp32_4M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Development.build_flags}
                            -DAFE_CONFIG_API_DOMOTICZ_ENABLED

[env:AFE_T4_esp32_4m_38P-ha]
extends                   = esp32_4M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP32_Production.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Production.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED

[env:AFE_T4_esp32_4m_38P-ha-development]
extends                   = esp32_4M
lib_deps                  = ${common-t4.lib_deps}
lib_ignore                = ${AFE_T4_ESP32_Development.lib_ignore}
build_flags               = ${AFE_T4_ESP32_Development.build_flags}
                             -DAFE_CONFIG_API_HOME_ASSISTANT_ENABLED
