#ifndef _AFE_Hardware_IIC_h
#define _AFE_Hardware_IIC_h

#define AFE_CONFIG_HARDWARE_I2C_DEFAULT_NON_EXIST_ADDRESS 0

/* Default configuration for iECS Gate */
#ifdef AFE_DEVICE_iECS_GATE_DRIVERv3

#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SDA 1
#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SCL 3
#else

#ifdef AFE_ESP32
#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SDA 21
#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SCL 22
#define AFE_CONFIG_HARDWARE_I2C_1_DEFAULT_SDA 27
#define AFE_CONFIG_HARDWARE_I2C_1_DEFAULT_SCL 26
#define AFE_CONFIG_HARDWARE_I2C_LOW_FREQUENCY 100000
#define AFE_CONFIG_HARDWARE_I2C_HIGH_FREQUENCY 400000
#define AFE_CONFIG_HARDWARE_I2C_DEFAULT_FREQUENCY AFE_CONFIG_HARDWARE_I2C_LOW_FREQUENCY
#else // ESP8266
#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SDA 4
#define AFE_CONFIG_HARDWARE_I2C_0_DEFAULT_SCL 5
#endif

#endif



#endif // _AFE_Hardware_IIC_h