#ifndef _AFE_Hardware_api_http_h
#define _AFE_Hardware_api_http_h

#define AFE_CONFIG_HTTP_DEVICE_RELAY "relay"
#define AFE_CONFIG_HTTP_DEVICE_ANALOG_INPUT "ADC"
#define AFE_CONFIG_HTTP_DEVICE_BATTERY_METER "batterymeter"
#define AFE_CONFIG_HTTP_DEVICE_BMEX80 "BMEX80"
#define AFE_CONFIG_HTTP_DEVICE_BMX80 "BMX80"
#define AFE_CONFIG_HTTP_DEVICE_BH1750 "BH1750"
#define AFE_CONFIG_HTTP_DEVICE_AS3935 "AS3935"
#define AFE_CONFIG_HTTP_DEVICE_HPMA115S0 "HPMA115S0"
#define AFE_CONFIG_HTTP_DEVICE_ANEMOMETER "anemometer"
#define AFE_CONFIG_HTTP_DEVICE_RAINMETER "rainmeter"
#define AFE_CONFIG_HTTP_DEVICE_GATE "gate"
#define AFE_CONFIG_HTTP_DEVICE_CONTACTRON "contactron"
#define AFE_CONFIG_HTTP_DEVICE_DS18B20 "ds18b20"
#define AFE_CONFIG_HTTP_DEVICE_REGULATOR "regulator"
#define AFE_CONFIG_HTTP_DEVICE_THERMAL_PROTECTOR "thermalProtector"
#define AFE_CONFIG_HTTP_DEVICE_DHT "dht"
#define AFE_CONFIG_HTTP_DEVICE_BINARY_SENSOR "binary"
#define AFE_CONFIG_HTTP_DEVICE_TSL2561 "tls2561"
#define AFE_CONFIG_HTTP_DEVICE_CLED "cled"
#define AFE_CONFIG_HTTP_DEVICE_CLED_EFFECT_WAVE "waveEffect"
#define AFE_CONFIG_HTTP_DEVICE_CLED_EFFECT_FADE_IN_OUT "fadeEffect"
#define AFE_CONFIG_HTTP_DEVICE_CLED_EFFECT_BLINKING "flashEffect"
#define AFE_CONFIG_HTTP_DEVICE_FS3000 "fs3000"

#define AFE_CONFIG_HTTP_COMMAND_REBOOT "reboot"
#define AFE_CONFIG_HTTP_COMMAND_CONFIGURATION_MODE "configurationMode"


#endif // _AFE_Hardware_api_http_h