#ifndef _AFE_Hardware_rainmeter_h
#define _AFE_Hardware_rainmeter_h

#define AFE_HARDWARE_RAINMETER_DEFAULT_BOUNCING 1
#define AFE_HARDWARE_RAINMETER_DEFAULT_INTERVAL 60
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_20) || defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_HARDWARE_RAINMETER_DEFAULT_GPIO 13
#define AFE_HARDWARE_RAINMETER_DEFAULT_RESOLUTION 172.5
#else
#define AFE_HARDWARE_RAINMETER_DEFAULT_GPIO 13
#define AFE_HARDWARE_RAINMETER_DEFAULT_RESOLUTION 172.5
#endif
#define AFE_CONFIG_API_JSON_RAINMETER_DATA_LENGTH 160 // Orginal 150 added 10

#endif // _AFE_Hardware_rainmeter_h