#ifndef _AFE_Hardware_ADC_h
#define _AFE_Hardware_ADC_h

#define AFE_CONFIG_API_JSON_ADC_DATA_LENGTH 200

#ifdef AFE_ESP32
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_GPIO AFE_HARDWARE_ITEM_NOT_EXIST
#else // ESP8266
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_GPIO 17
#endif 

#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_INTERVAL 60
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_NUMBER_OF_SAMPLES 1
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_MAX_VCC 1

/* Baterymeter */
#ifdef AFE_CONFIG_FUNCTIONALITY_BATTERYMETER
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_BATTER_MIN_V 3
#define AFE_CONFIG_HARDWARE_ANALOG_INPUT_DEFAULT_BATTER_MAX_V 4.2
#define AFE_CONFIG_API_JSON_BATTERYMETER_DATA_LENGTH 200
#endif

#endif // _AFE_Hardware_ADC_h