/* AFE Firmware for smart home devices, Website: https://afe.smartnydom.pl/ */

#ifndef _AFE_Configuration_h
#define _AFE_Configuration_h

/* Serial port speed */
//#define AFE_CONFIG_SERIAL_SPEED 9600
#define AFE_CONFIG_SERIAL_SPEED 115200

/* Max size of the configuration HTML page */
#define AFE_MAX_PAGE_SIZE 12000

/* Upgrade types */
#define AFE_UPGRADE_NONE 0
#define AFE_UPGRADE_VERSION 1
#define AFE_UPGRADE_VERSION_TYPE 2

/* Device operating modes */
#define AFE_MODE_NORMAL 0
#define AFE_MODE_CONFIGURATION 1
#define AFE_MODE_ACCESS_POINT 2
#define AFE_MODE_NETWORK_NOT_SET 4
#define AFE_MODE_FIRST_TIME_LAUNCH 5

/* APIs */
#define AFE_API_STANDARD 0
#define AFE_API_DOMOTICZ 1

/* URLs to AFE WebService */
#define AFE_URL_VALIDATE_KEY "http://api.smartnydom.pl/key/validate/"
#define AFE_URL_ADD_KEY "http://api.smartnydom.pl/key/add/"
#define AFE_KEY_FREQUENCY_VALIDATION 60 // 1440

/* Types of URL requests */
#define AFE_SERVER_CMD_SAVE 1
#define AFE_SERVER_CMD_NONE 0

/* File system */
#define AFE_FS_SPIFFS 0
#define AFE_FS_LITTLEFS 1

/* Not existing hardware item. Used as a default value */
#define AFE_HARDWARE_ITEM_NOT_EXIST 255

/* Empty string */
#define AFE_EMPTY_STRING '\0'

/* Default time to auto-logout from config panel: in minutes */
#define AFE_AUTOLOGOFF_DEFAULT_TIME 10

/* Number of GPIOs available in ESP8266, used in the conjunction with
 * AFE-Site-components.h table */
#define AFE_NUMBER_OF_GPIOS 13

/* Types of the devices */
#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_DEVICE_TYPE_NAME "Sonoff Basic V1"
#define AFE_DEVICE_TYPE_ID 1
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_DEVICE_TYPE_NAME "Sonoff 4CH"
#define AFE_DEVICE_TYPE_ID 2
#elif defined(AFE_DEVICE_SONOFF_DUAL_R2)
#define AFE_DEVICE_TYPE_NAME "Sonoff Dual R2"
#define AFE_DEVICE_TYPE_ID 3
#elif defined(AFE_DEVICE_SONOFF_TH10)
#define AFE_DEVICE_TYPE_NAME "Sonoff TH10"
#define AFE_DEVICE_TYPE_ID 4
#elif defined(AFE_DEVICE_SONOFF_TH16)
#define AFE_DEVICE_TYPE_NAME "Sonoff TH16"
#define AFE_DEVICE_TYPE_ID 5
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_DEVICE_TYPE_NAME "Sonoff Touch 1G"
#define AFE_DEVICE_TYPE_ID 6
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_DEVICE_TYPE_NAME "Sonoff Touch 2G"
#define AFE_DEVICE_TYPE_ID 7
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_DEVICE_TYPE_NAME "Sonoff Touch 3G"
#define AFE_DEVICE_TYPE_ID 8
#elif defined(AFE_DEVICE_SHELLY_1)
#define AFE_DEVICE_TYPE_NAME "Shelly 1"
#define AFE_DEVICE_TYPE_ID 20
#elif defined(AFE_DEVICE_iECSv20)
#define AFE_DEVICE_TYPE_NAME "iECS Gate Controller v2"
#define AFE_DEVICE_TYPE_ID 21
#elif defined(AFE_DEVICE_iECS_WHEATER_STATION_20)
#define AFE_DEVICE_TYPE_NAME "iECS Weather Station v2"
#define AFE_DEVICE_TYPE_ID 22
#elif defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_DEVICE_TYPE_NAME "iECS Weather Station v2.1"
#define AFE_DEVICE_TYPE_ID 23
#else
#define AFE_DEVICE_TYPE_NAME "ESP Generic"
#define AFE_DEVICE_TYPE_ID 0
#endif

/* ##### AFE VERSIONS ##### */

/* ---- Basic Switch ---- */
#if defined(T0_CONFIG)
#define AFE_FIRMWARE_VERSION "2.5.1"
#define AFE_FIRMWARE_TYPE 0

/* Define Hardware */
#define AFE_CONFIG_HARDWARE_SWITCH

#ifndef AFE_DEVICE_SHELLY_1
#define AFE_CONFIG_HARDWARE_LED
#endif

/* Max number of hardware items, per AFE version */
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 5
#ifdef AFE_CONFIG_HARDWARE_LED
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 5
#endif

/* Max number of hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 4
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 2
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 4
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SHELLY_1)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_SWITCH_GPIO_DIGIT_INPUT // Sets switch Digitial PIN
                                                    // to INPUT
/* Generic version */
#else
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 5
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 5
#endif

/* Default values for hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 4
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 2
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 2
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 3
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#elif defined(AFE_DEVICE_SHELLY_1)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 0
#define AFE_CONFIG_HARDWARE_SWITCH_GPIO_DIGIT_INPUT // Sets switch DigitialPin
                                                    // to INPUT
/* Generic version */
#else
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#endif

/* Functionalities */
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF

/* ADC Is not applicable for Shelly-1 */
#ifndef AFE_DEVICE_SHELLY_1
#define AFE_CONFIG_FUNCTIONALITY_ADC
#endif // AFE_DEVICE_SHELLY_1

/* ---- Basic Switch + DS18B20 ---- */
#elif defined(T1_CONFIG)
#define AFE_FIRMWARE_VERSION "2.5.0"
#define AFE_FIRMWARE_TYPE 1

/* File system used */
#define AFE_FILE_SYSTEM AFE_FS_SPIFFS

/* Functionalities */
#ifndef AFE_T1_CUSTOM_E1
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_CONFIG_FUNCTIONALITY_ADC
#endif

/* Define Hardware */
#define AFE_CONFIG_HARDWARE_SWITCH
#define AFE_CONFIG_HARDWARE_DS18B20
#define AFE_CONFIG_HARDWARE_LED

/* Max number of hardware items, per AFE version */
#if defined(AFE_CONFIG_USE_MAX_HARDWARE)
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20 8
#elif defined(AFE_T1_CUSTOM_E1)
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20 30
#else
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 5
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 5
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20 8
#endif

#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_DS18B20 AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20

#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_DS18B20 0

#ifdef AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_REGULATORS AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_REGULATORS AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_REGULATORS 0
#endif

#ifdef AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_THERMAL_PROTECTOR AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_THERMAL_PROTECTORS AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_THERMAL_PROTECTIORS 0
#endif

/* ---- Basic Switch + DTHxx ---- */
#elif defined(T2_CONFIG)
#define AFE_FIRMWARE_VERSION "2.5.0"
#define AFE_FIRMWARE_TYPE 2

/* File system used */
#define AFE_FILE_SYSTEM AFE_FS_SPIFFS

/* Functionalities */
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_CONFIG_FUNCTIONALITY_ADC

/* Define Hardware */
#define AFE_CONFIG_HARDWARE_SWITCH
#define AFE_CONFIG_HARDWARE_DHT
#define AFE_CONFIG_HARDWARE_LED

/* Max number of hardware items, per AFE version */
#ifdef AFE_CONFIG_USE_MAX_HARDWARE
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 8
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DHT 8
#else
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 4
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 5
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 5
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DHT 4
#endif

#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS                                   \
  AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES                                 \
  AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS                                     \
  AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_DHT AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DHT

#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_DHT 0

#ifdef AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_REGULATORS                           \
  AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_REGULATORS                               \
  AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_REGULATORS 0
#endif

#ifdef AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_THERMAL_PROTECTOR                    \
  AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_THERMAL_PROTECTORS                       \
  AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_THERMAL_PROTECTIORS 0
#endif

/* ---- 4xRelay + PIR ---- */
#elif defined(T3_CONFIG)
#define AFE_FIRMWARE_TYPE 3
#define AFE_FIRMWARE_VERSION "1.3.0"
#define AFE_CONFIG_HARDWARE_PIR
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_CONTROL_AUTOONOFF_TIME

/* ---- 4xRelay MCP23017 ---- */
#elif defined(T4_CONFIG)
#define AFE_FIRMWARE_VERSION "2.5.0"
#define AFE_FIRMWARE_TYPE 4

#define AFE_FILE_SYSTEM AFE_FS_SPIFFS

/* Define Hardware */
#define AFE_CONFIG_HARDWARE_SWITCH
#define AFE_CONFIG_HARDWARE_LED
#define AFE_CONFIG_HARDWARE_MCP23017
#define AFE_CONFIG_HARDWARE_BINARY_SENSOR
#define AFE_CONFIG_HARDWARE_DS18B20

/* Max number of hardware items, per AFE version */
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 32
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 32
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 32
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BINARY_SENSORS 32
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_MCP23017 2
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20 1

/* Max number of hardware items per specyfic hardware device */
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_MCP23017 AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_MCP23017
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BINARY_SENSORS AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BINARY_SENSORS
#define AFE_CONFIG_HARDWARE_NUMBER_OF_DS18B20 AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_DS18B20

/* Generic version */
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BINARY_SENSORS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_DS18B20 0

/* Functionalities */
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_ADC


/* ---- Gate ----*/
#elif defined(T5_CONFIG)
#define AFE_FIRMWARE_VERSION "2.4.0"
#define AFE_FIRMWARE_TYPE 5

/* Define Hardware */
#define AFE_CONFIG_HARDWARE_SWITCH
#define AFE_CONFIG_HARDWARE_LED
#define AFE_CONFIG_FUNCTIONALITY_ADC

#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_BMEX80
#define AFE_CONFIG_HARDWARE_BH1750
#endif // ESP_4MB

/* Max number of hardware items per AFE version */
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 2
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 3
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_CONTACTRONS 4
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_GATES 2
// Sensors only available in 4MB Flash
#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BH1750 1
#endif

/* Max number of hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_iECSv20)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_CONTACTRONS 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_GATES 2
// Sensors only available in 4MB Flash
#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BH1750 1
#endif
/* Generic version */
#else
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_CONTACTRONS 4
#define AFE_CONFIG_HARDWARE_NUMBER_OF_GATES 2
// Sensors only available in 4MB Flash
#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BH1750 1
#endif
#endif

/* Default values for hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_iECSv20)
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_CONTACTRONS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_GATES 1
// Sensors only available in 4MB Flash
#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BMEX80 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BH1750 0
#endif
#else
/* Generic version */
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_CONTACTRONS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_GATES 0
// Sensors only available in 4MB Flash
#ifdef ESP_4MB
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BMEX80 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BH1750 0
#endif
#endif

/* Functionalities */
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_RELAY_CONTROL_AUTOONOFF_TIME
#define AFE_CONFIG_FUNCTIONALITY_GATE
#define AFE_CONFIG_FUNCTIONALITY_ADC

/* ---- Wheater Station ---- */
#elif defined(T6_CONFIG)
#define AFE_FIRMWARE_VERSION "2.5.1.B1"
#define AFE_FIRMWARE_TYPE 6

/* Functionalities */
#define AFE_CONFIG_FUNCTIONALITY_RELAY
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_ADC
#define AFE_CONFIG_FUNCTIONALITY_BATTERYMETER

#define AFE_FILE_SYSTEM AFE_FS_SPIFFS

#define AFE_CONFIG_HARDWARE_SWITCH
#define AFE_CONFIG_HARDWARE_LED
#define AFE_CONFIG_HARDWARE_BMEX80
#define AFE_CONFIG_HARDWARE_HPMA115S0
#define AFE_CONFIG_HARDWARE_BH1750
//#define AFE_CONFIG_HARDWARE_AS3935
//#define AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR
//#define AFE_CONFIG_HARDWARE_RAINMETER_SENSOR

/* Max number of hardware items, per AFE version */
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_LEDS 2
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_HPMA115S0 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_BH1750 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_AS3935 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_ANEMOMETER_SENSORS 1
#define AFE_CONFIG_HARDWARE_MAX_NUMBER_OF_RAINMETER_SENSORS 1

/* Max number of hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_20) ||                             \
    defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_HPMA115S0 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BH1750 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_AS3935 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_ANEMOMETER_SENSORS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RAINMETER_SENSORS 1
#else
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RELAYS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_SWITCHES 3
#define AFE_CONFIG_HARDWARE_NUMBER_OF_LEDS 2
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BMEX80 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_HPMA115S0 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_BH1750 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_AS3935 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_ANEMOMETER_SENSORS 1
#define AFE_CONFIG_HARDWARE_NUMBER_OF_RAINMETER_SENSORS 1
#endif // AFE_DEVICE_iECS_WHEATER_STATION_20

/* Default values for hardware items per specyfic hardware device */
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_20) ||                             \
    defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
/* Whater Station V2 */
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BMEX80 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_HPMA115S0 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BH1750 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_AS3935 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_ANEMOMETER_SENSORS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RAINMETER_SENSORS 0
#else
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RELAYS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_SWITCHES 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_LEDS 1
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BMEX80 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_HPMA115S0 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_BH1750 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_AS3935 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_ANEMOMETER_SENSORS 0
#define AFE_CONFIG_HARDWARE_DEFAULT_NUMBER_OF_RAINMETER_SENSORS 0
#endif // AFE_DEVICE_iECS_WHEATER_STATION_20

#endif // defined(T6_CONFIG)

/* File system */
#ifndef AFE_FILE_SYSTEM_USED
#define AFE_FILE_SYSTEM_USED AFE_FS_SPIFFS
#endif
 

/* Configs related to a relay functionality */
#ifdef AFE_CONFIG_FUNCTIONALITY_RELAY
#ifndef AFE_CONFIG_HARDWARE_RELAY
#define AFE_CONFIG_HARDWARE_RELAY
#endif
#endif // AFE_CONFIG_FUNCTIONALITY_RELAY

/* Config releated to battery meter functionality */
#ifdef AFE_CONFIG_FUNCTIONALITY_BATTERYMETER
#ifndef AFE_CONFIG_HARDWARE_ADC_VCC
#define AFE_CONFIG_HARDWARE_ADC_VCC
#endif
#endif // AFE_CONFIG_FUNCTIONALITY_BATTERYMETER

/* Configs related to analog input functionality */
#ifdef AFE_CONFIG_FUNCTIONALITY_ADC
#ifndef AFE_CONFIG_HARDWARE_ADC_VCC
#define AFE_CONFIG_HARDWARE_ADC_VCC
#endif
#endif // AFE_CONFIG_FUNCTIONALITY_ADC

/* Configs related to a gate functionality */
#ifdef AFE_CONFIG_FUNCTIONALITY_GATE
#ifndef AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#endif
#ifndef AFE_CONFIG_HARDWARE_RELAY
#define AFE_CONFIG_HARDWARE_RELAY
#endif
#ifndef AFE_CONFIG_HARDWARE_GATE
#define AFE_CONFIG_HARDWARE_GATE
#endif
#ifndef AFE_CONFIG_HARDWARE_CONTACTRON
#define AFE_CONFIG_HARDWARE_CONTACTRON
#endif
#endif // AFE_CONFIG_FUNCTIONALITY_GATE

#ifdef AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR
#endif // AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR

/* ***************** HARDWARE: Config and defaults *********************/

/* MCP23017 GPIO extension board */
#ifdef AFE_CONFIG_HARDWARE_MCP23017
#ifndef AFE_CONFIG_HARDWARE_I2C
#define AFE_CONFIG_HARDWARE_I2C
#endif

#define AFE_NUMBER_OF_MCP23017_GPIOS 16

#endif // AFE_CONFIG_HARDWARE_MCP23017

/* LED */
#ifdef AFE_CONFIG_HARDWARE_LED
#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#define AFE_CONFIG_HARDWARE_LED_1_DEFAULT_GPIO 14
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_DUAL_R2)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_TH10)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_TH16)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 13
#elif defined(AFE_DEVICE_iECSv20)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 2
#elif defined(AFE_DEVICE_WHEATER_STATION_iECSv20) ||                           \
    defined(AFE_DEVICE_WHEATER_STATION_iECSv21)
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 2
#else
#define AFE_CONFIG_HARDWARE_LED_0_DEFAULT_GPIO 2
#endif
#endif // AFE_CONFIG_HARDWARE_LED

/* SWITCH */
#ifdef AFE_CONFIG_HARDWARE_SWITCH
/* Switches, types */
#define AFE_SWITCH_TYPE_MONO 0 // Mono stable switch
#define AFE_SWITCH_TYPE_BI 1   // Bistable switch

/* Switch ON/OFF Values */
#define AFE_SWITCH_ON 1
#define AFE_SWITCH_OFF 0

/* Switches functionalities */
#define AFE_SWITCH_FUNCTIONALITY_NONE 0  // does nothibg
#define AFE_SWITCH_FUNCTIONALITY_MULTI 1 // System switch and relay control
#define AFE_SWITCH_FUNCTIONALITY_RELAY 2 // Relay control

/* Switche bouncing */
#define AFE_HARDWARE_SWITCH_DEFAULT_BOUNCING 50 // Bouncing for switch in miliseconds

#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 14
#define AFE_HARDWARE_SWITCH_2_DEFAULT_GPIO 1
#define AFE_HARDWARE_SWITCH_3_DEFAULT_GPIO 3
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_BI // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 9
#define AFE_HARDWARE_SWITCH_2_DEFAULT_GPIO 10
#define AFE_HARDWARE_SWITCH_3_DEFAULT_GPIO 14
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
// actually below 2 doesn't matter, they're needed to pharse the firmware ;)
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 9
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 9
#define AFE_HARDWARE_SWITCH_2_DEFAULT_GPIO 10
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_SHELLY_1)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 5
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_BI
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY
// actually below 2 doesn't matter, they're needed to pharse the firmware ;)
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_RELAY // Default for all switches exlcuding the first
                                 // one
#elif defined(AFE_DEVICE_iECSv20)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 1
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_NONE // Default for all switches exlcuding the first
                                // one
#elif defined(AFE_DEVICE_iECS_WHEATER_STATION_20) ||                           \
    defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 14
#define AFE_HARDWARE_SWITCH_2_DEFAULT_GPIO 13
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_MONO // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_NONE // Default for all switches exlcuding the first
                                // one
#else
#define AFE_HARDWARE_SWITCH_0_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_1_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_2_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_3_DEFAULT_GPIO 0
#define AFE_HARDWARE_SWITCH_0_DEFAULT_TYPE AFE_SWITCH_TYPE_MONO
#define AFE_HARDWARE_SWITCH_X_DEFAULT_TYPE                                     \
  AFE_SWITCH_TYPE_BI // Default for all switches exlcuding the first one
#define AFE_HARDWARE_SWITCH_0_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_MULTI
#define AFE_HARDWARE_SWITCH_X_DEFAULT_FUNCTIONALITY                            \
  AFE_SWITCH_FUNCTIONALITY_NONE // Default for all switches exlcuding the first
                                // one
#endif

#endif // AFE_CONFIG_HARDWARE_SWITCH

/* RELAY */
#ifdef AFE_CONFIG_HARDWARE_RELAY

/* Relay ON/OFF values */
#define AFE_RELAY_ON 1
#define AFE_RELAY_OFF 0

#define AFE_RELAY_SIGNAL_TRIGGER_HIGH 1
#define AFE_RELAY_SIGNAL_TRIGGER_LOW 0

#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_SIGNAL_TRIGGER                       \
  AFE_RELAY_SIGNAL_TRIGGER_HIGH

#if defined(AFE_DEVICE_SONOFF_BASIC_V1)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "relay"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_SONOFF_4CH)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_GPIO 5
#define AFE_CONFIG_HARDWARE_RELAY_2_DEFAULT_GPIO 4
#define AFE_CONFIG_HARDWARE_RELAY_3_DEFAULT_GPIO 15
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "R1"
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_NAME "R2"
#define AFE_CONFIG_HARDWARE_RELAY_2_DEFAULT_NAME "R3"
#define AFE_CONFIG_HARDWARE_RELAY_3_DEFAULT_NAME "R4"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_SONOFF_TOUCH_1G)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "relay"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_SONOFF_TOUCH_2G)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_GPIO 5
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "R1"
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_NAME "R2"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_SONOFF_TOUCH_3G)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_GPIO 5
#define AFE_CONFIG_HARDWARE_RELAY_2_DEFAULT_GPIO 4
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "R1"
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_NAME "R2"
#define AFE_CONFIG_HARDWARE_RELAY_2_DEFAULT_NAME "R3"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_SHELLY_1)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 4
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "relay"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_iECSv20)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 15
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "R1"
#define AFE_CONFIG_HARDWARE_RELAY_1_DEFAULT_NAME "R2"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 200
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 0
#elif defined(AFE_DEVICE_iECS_WHEATER_STATION_20)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "relay"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#elif defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 15
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_NAME "relay"
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3

#else
#define AFE_CONFIG_HARDWARE_RELAY_0_DEFAULT_GPIO 12
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_TIME_TO_OFF 0
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_POWER_ON 3
#endif

#endif // AFE_CONFIG_HARDWARE_RELAY

#ifdef AFE_CONFIG_HARDWARE_BINARY_SENSOR
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_BOUNCING 10
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_REVERT_SIGNAL false
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_SENT_AS_SWITCH false
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_INTERNAL_PULLUP_RESISTOR true
#define AFE_CONFIG_API_JSON_BINARY_SENSOR_DATA_LENGTH 19 // {"state":"closed"}
#endif // AFE_CONFIG_HARDWARE_BINARY_SENSOR

/* DS18B20 Sensor */
#ifdef AFE_CONFIG_HARDWARE_DS18B20
#ifndef AFE_CONFIG_TEMPERATURE
#define AFE_CONFIG_TEMPERATURE
#endif // AFE_CONFIG_HARDWARE_DS18B20

#define AFE_CONFIG_HARDWARE_DS18B20_DEFAULT_GPIO 14
#define AFE_CONFIG_HARDWARE_DS18B20_DEFAULT_INTERVAL 60
#define AFE_CONFIG_HARDWARE_DS18B20_DEFAULT_SENDING_ONLY_CHANGES false
#define AFE_CONFIG_HARDWARE_DS18B20_DEFAULT_TEMPERATURE_CORRECTION 0
#define AFE_CONFIG_HARDWARE_DS18B20_DEFAULT_RESOLUTION 12
#define AFE_CONFIG_HARDWARE_DS18B20_ADDRESS_LENGTH 8
#define AFE_CONFIG_HARDWARE_DS18B20_READ_TIMEOUT 10000

#define AFE_CONFIG_API_JSON_DS18B20_DATA_LENGTH 46 // {"temperature":{"value":-999.999,"unit":"C"}}
#endif

/* DHxx sesnors like DHT21,DHT22 */
#ifdef AFE_CONFIG_HARDWARE_DHT
#ifndef AFE_CONFIG_TEMPERATURE
#define AFE_CONFIG_TEMPERATURE
#endif
#ifndef AFE_CONFIG_HUMIDITY
#define AFE_CONFIG_HUMIDITY
#endif

#define AFE_CONFIG_HARDWARE_DHT_TYPE_AUTO 0
#define AFE_CONFIG_HARDWARE_DHT_TYPE_DHT11 1
#define AFE_CONFIG_HARDWARE_DHT_TYPE_DHT22 2
#define AFE_CONFIG_HARDWARE_DHT_TYPE_AM2302 3
#define AFE_CONFIG_HARDWARE_DHT_TYPE_RHT03 4

#define AFE_CONFIG_HARDWARE_DHT_DEFAULT_GPIO 14
#define AFE_CONFIG_HARDWARE_DHT_DEFAULT_INTERVAL 60
#define AFE_CONFIG_HARDWARE_DHT_DEFAULT_SENDING_ONLY_CHANGES false
#define AFE_CONFIG_HARDWARE_DHT_DEFAULT_TEMPERATURE_CORRECTION 0
#define AFE_CONFIG_HARDWARE_DHT_DEFAULT_HUMIDITY_CORRECTION 0
//#define AFE_CONFIG_HARDWARE_DS18B20_READ_TIMEOUT 10000
#define AFE_CONFIG_API_JSON_DHT_DATA_LENGTH                                    \
  420 // {"temperature":{"value":218.4,"unit":"C"},"humidity":{"value":317.0,"unit":"%"},"absoluteHumidity":{"value":110.29,"unit":"%"},"heatIndex":{"value":217.81,"unit":"C"},"dewPoint":{"value":112.33,"unit":"C"},"perception":{"value":1,"description":"W porządku dla większości, ale wszyscy odczuwają wilgoć przy górnej krawędzi"},"comfort":{"value":0,"ratio":100.00,"unit":"%","description":"Gorąco i wilgotno"}} 

#endif // AFE_CONFIG_HARDWARE_DHT

/* BMEX80 Sensors */
#ifdef AFE_CONFIG_HARDWARE_BMEX80
#ifndef AFE_CONFIG_TEMPERATURE
#define AFE_CONFIG_TEMPERATURE
#endif
#ifndef AFE_CONFIG_HUMIDITY
#define AFE_CONFIG_HUMIDITY
#endif
#ifndef AFE_CONFIG_PRESSURE
#define AFE_CONFIG_PRESSURE
#endif
#ifndef AFE_CONFIG_HARDWARE_I2C
#define AFE_CONFIG_HARDWARE_I2C
#endif
#ifndef AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#define AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#endif
#endif // AFE_CONFIG_HARDWARE_BMEX80

/* BH1750 Sensor */
#ifdef AFE_CONFIG_HARDWARE_BH1750
#ifndef AFE_CONFIG_HARDWARE_I2C
#define AFE_CONFIG_HARDWARE_I2C
#endif
#endif // AFE_CONFIG_HARDWARE_BH1750

/* AS3935 Sensor */
#ifdef AFE_CONFIG_HARDWARE_AS3935

/* Distance units */
#define AFE_DISTANCE_KM 1
#define AFE_DISTANCE_MIL 2

#ifndef AFE_CONFIG_HARDWARE_I2C
#define AFE_CONFIG_HARDWARE_I2C
#endif
#endif // AFE_CONFIG_HARDWARE_AS3935

/* HPMA115S0 Sensor */
#ifdef AFE_CONFIG_HARDWARE_HPMA115S0
#define HPMA115S0_TYPE_PM25 0
#define HPMA115S0_TYPE_PM10 1
#ifndef AFE_CONFIG_HARDWARE_UART
#define AFE_CONFIG_HARDWARE_UART
#endif
#ifndef AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#define AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#endif
#endif // AFE_CONFIG_HARDWARE_HPMA115S0

/* ADC Input */
#ifdef AFE_CONFIG_HARDWARE_ADC_VCC
#define AFE_CONFIG_API_JSON_ADC_DATA_LENGTH 200
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_GPIO 17
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_INTERVAL 60
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_NUMBER_OF_SAMPLES 1
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_MAX_VCC 1
#endif // AFE_CONFIG_HARDWARE_ADC_VCC

/* Baterymeter */
#ifdef AFE_CONFIG_FUNCTIONALITY_BATTERYMETER
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_BATTER_MIN_V 3
#define AFE_CONFIG_HARDWARE_ADC_VCC_DEFAULT_BATTER_MAX_V 4.2
#define AFE_CONFIG_API_JSON_BATTERYMETER_DATA_LENGTH 200
#endif // AFE_CONFIG_FUNCTIONALITY_BATTERYMETER

/* PIR Sesnor */
#ifdef AFE_CONFIG_HARDWARE_PIR
#ifndef AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#define AFE_CONFIG_FUNCTIONALITY_RELAY_AUTOONOFF
#endif
#endif // AFE_CONFIG_HARDWARE_PIR

/* Gate */
#ifdef AFE_CONFIG_HARDWARE_GATE
/* Gate's states */
#define AFE_GATE_OPEN 0           // Open
#define AFE_GATE_CLOSED 1         // Closed
#define AFE_GATE_PARTIALLY_OPEN 2 // Being opened
#define AFE_GATE_UNKNOWN 9        // Unknown state

/* Gate MQTT messages */
#define AFE_MQTT_GATE_OPEN "open"
#define AFE_MQTT_GATE_CLOSED "closed"
#define AFE_MQTT_GATE_PARTIALLY_OPEN "partiallyOpen"
#define AFE_MQTT_GATE_UNKNOWN "unknown"

#define AFE_CONFIG_API_JSON_GATE_DATA_LENGTH                                   \
  200 // Not checked, used by HTTP API

#endif // AFE_CONFIG_HARDWARE_GATE

/* Contactron */
#ifdef AFE_CONFIG_HARDWARE_CONTACTRON
/* Contactron types */
#define AFE_CONTACTRON_NO 0 // Normally open
#define AFE_CONTACTRON_NC 1 // Normally closed
/* Contactron states */
#define AFE_CONTACTRON_OPEN 0   // Open
#define AFE_CONTACTRON_CLOSED 1 // Closed
/* Contactron defaults */
#define AFE_CONFIG_HARDWARE_CONTACTRON_DEFAULT_BOUNCING 200
#define AFE_CONFIG_HARDWARE_CONTACTRON_DEFAULT_OUTPUT_TYPE AFE_CONTACTRON_NO
/* Contactron MQTT messages */
#define AFE_MQTT_CONTACTRON_OPEN "open"
#define AFE_MQTT_CONTACTRON_CLOSED "closed"

#define AFE_CONFIG_API_JSON_CONTACTRON_DATA_LENGTH 200  // Not checked. used by HTTP API
#endif // AFE_CONFIG_HARDWARE_CONTACTRON

/* Temperature */
#ifdef AFE_CONFIG_TEMPERATURE
#define AFE_TEMPERATURE_UNIT_CELSIUS 1
#define AFE_TEMPERATURE_UNIT_FAHRENHEIT 2
#define AFE_TEMPERATURE_UNIT_KELVIN 3
#endif // AFE_CONFIG_TEMPERATURE

/* Humidity */
#ifdef AFE_CONFIG_HUMIDITY
typedef enum {
  AFE_HUMIDITY_EXCELLENT = 1,
  AFE_HUMIDITY_GOOD = 2,
  AFE_HUMIDITY_FAIR = 3,
  AFE_HUMIDITY_POOR = 4,
  AFE_HUMIDITY_INADEQUATE = 5
} afe_humidity_ratings_t;

#define AFE_HUMIDITY_UNIT 1

#endif // AFE_CONFIG_HUMIDITY

/* Pressure */
#ifdef AFE_CONFIG_PRESSURE
#define AFE_CONFIG_DEFAULT_SEA_LEVEL_PRESSURE 1013.25
#define AFE_PRESSURE_UNIT_HPA 1
#endif // AFE_CONFIG_PRESSURE

/* UART Defaults */
#ifdef AFE_CONFIG_HARDWARE_UART
#define AFE_CONFIG_HARDWARE_UART_DEFAULT_RXD 3
#define AFE_CONFIG_HARDWARE_UART_DEFAULT_TXD 1
#endif // AFE_CONFIG_HARDWARE_UART

/* I2C Defaults */
#ifdef AFE_CONFIG_HARDWARE_I2C
#define AFE_CONFIG_HARDWARE_I2C_DEFAULT_SDA 4
#define AFE_CONFIG_HARDWARE_I2C_DEFAULT_SCL 5
#define AFE_CONFIG_HARDWARE_I2C_DEFAULT_NON_EXIST_ADDRESS 0
#endif // AFE_CONFIG_HARDWARE_I2C

/* HPMA115S0 Defaults */
#ifdef AFE_CONFIG_HARDWARE_HPMA115S0
#define AFE_CONFIG_HARDWARE_HPMA115S_DEFAULT_INTERVAL 300
#define AFE_CONFIG_HARDWARE_HPMA115S_DEFAULT_TIME_TO_MEASURE 0
#define AFE_CONFIG_API_JSON_HPMA115S0_DATA_LENGTH 220
#endif // AFE_CONFIG_HARDWARE_HPMA115S0

/* BMx80 Defaults */
#ifdef AFE_CONFIG_HARDWARE_BMEX80
#define AFE_CONFIG_HARDWARE_BMEX80_DEFAULT_INTERVAL 60
#define AFE_CONFIG_API_JSON_BMEX80_DATA_LENGTH 1195 // {"temperature":{"value":25.0273,"unit":"C","correction":25.0273},"pressure":{"value":993.6063,"unit":"hPa","correction":993.6063},"relativePressure":{"value":1003.809,"unit":"hPa"},"dewPoint":{"value":5.321408,"unit":"C"},"humidity":{"value":281.10078,"unit":"%H","correction":281.10078,"rating":3},"absoluteHumidity":{"value":6.480335,"unit":"%H"},"heatIndex":{"value":24.31934,"unit":"C"},"perception":{"value":0,"description":"W porządku dla większości, ale wszyscy odczuwają wilgoć przy górnej krawędzi"},"comfort":{"value":4,"ratio":84.7268,"unit":"%","description":"Gorąco i wilgotno"},"iaq":{"value":1110,"rating":1,"accuracy":0},"staticIaq":{"value":1110,"rating":1,"accuracy":0},"co2Equivalent":{"value":1400,"unit":"ppm","rating":1,"accuracy":0},"breathVocEquivalent":{"value":0.342646,"unit":"?","accuracy":0},"gasResistance":{"value":2324.371,"unit":"kOm"}}
#define AFE_BMX_UNKNOWN_SENSOR 255
#define AFE_BMP180_SENSOR 1
#define AFE_BME280_SENSOR 2
#define AFE_BME680_SENSOR 6

typedef enum {
  AFE_IAQ_GOOD = 1,
  AFE_IAQ_AVARAGE = 2,
  AFE_IAQ_LITTLE_BAD = 3,
  AFE_IAQ_BAD = 4,
  AFE_IAQ_WORSE = 5,
  AFE_IAQ_VERY_BAD = 5,
  AFE_IAQ_UNKNOWN = 255
} afe_iaq_ratings_t;

typedef enum {
  AFE_CO2_EXCELLENT = 1,
  AFE_CO2_GOOD = 2,
  AFE_CO2_FAIR = 3,
  AFE_CO2_POOR = 4,
  AFE_CO2_INADEQUATE = 5
} afe_co2_ratings_t;

#endif // AFE_CONFIG_HARDWARE_BMEX80

/* BH1750 Defualts */
#ifdef AFE_CONFIG_HARDWARE_BH1750
#define AFE_CONFIG_HARDWARE_BH1750_DEFAULT_INTERVAL 60
#define AFE_CONFIG_HARDWARE_BH1750_DEFAULT_MODE 0
#define AFE_CONFIG_API_JSON_BH1750_DATA_LENGTH 180
#endif // AFE_CONFIG_HARDWARE_BH1750

/* AS3935 Defaults */
#ifdef AFE_CONFIG_HARDWARE_AS3935
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_GPIO 12
#else
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_GPIO 0
#endif
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_WATCHDOG_THRESHOLD 1
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_MINIMUM_NO_OF_SPIKES 1
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_NOISE_FLOOR 1
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_MAX_NOISE_FLOOR 7
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_SPIKES_REJECTION_LEVEL 1
#define AFE_CONFIG_HARDWARE_AS3935_DEFAULT_UNKNOWN_DISTANCE 255
#define AFE_CONFIG_API_JSON_AS3935_DATA_LENGTH 200 // @TODO check it
#endif                                             // AFE_CONFIG_HARDWARE_AS3935

/* Anemometer Sensor Defaults */
#ifdef AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR
#define AFE_DISTANCE_CENTIMETER 0
#define AFE_DISTANCE_METER 1
#define AFE_DISTANCE_KILOMETER 2
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_BOUNCING 1
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_INTERVAL 60
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_20) ||                             \
    defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_GPIO 14
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_IMPULSE_DISTANCE 25
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_IMPULSE_DISTANCE_UNIT           \
  AFE_DISTANCE_CENTIMETER
#else
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_GPIO 14
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_IMPULSE_DISTANCE 25
#define AFE_HARDWARE_ANEMOMETER_SENSOR_DEFAULT_IMPULSE_DISTANCE_UNIT           \
  AFE_DISTANCE_CENTIMETER
#endif
#define AFE_CONFIG_API_JSON_ANEMOMETER_DATA_LENGTH 88 // Orginal 78 added 10
#endif // AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR

/* Rainmeter defaults */
#ifdef AFE_CONFIG_HARDWARE_RAINMETER_SENSOR
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_BOUNCING 1
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_INTERVAL 60
#if defined(AFE_DEVICE_iECS_WHEATER_STATION_20) ||                             \
    defined(AFE_DEVICE_iECS_WHEATER_STATION_21)
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_GPIO 13
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_RESOLUTION 172.5
#else
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_GPIO 13
#define AFE_HARDWARE_RAINMETER_SENSOR_DEFAULT_RESOLUTION 172.5
#endif
#define AFE_CONFIG_API_JSON_RAINMETER_DATA_LENGTH 160 // Orginal 150 added 10
#endif // AFE_CONFIG_HARDWARE_RAINMETER_SENSOR

/* Regulator defaults */
#ifdef AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_FUNCTIONALITY_REGULATOR_DEFAULT_ENABLED true
#define AFE_FUNCTIONALITY_REGULATOR_DEFAULT_ON 0
#define AFE_FUNCTIONALITY_REGULATOR_DEFAULT_OFF 0
#define AFE_FUNCTIONALITY_REGULATOR_DEFAULT_ON_INDICATOR false
#define AFE_FUNCTIONALITY_REGULATOR_DEFAULT_OFF_INDICATOR true
#define AFE_CONFIG_API_JSON_REGULATOR_DATA_LENGTH 18 // {"enabled":false}

#ifdef AFE_CONFIG_HARDWARE_DHT
#define AFE_FUNCTIONALITY_REGULATOR_CP_TEMPERATURE 0
#define AFE_FUNCTIONALITY_REGULATOR_CP_HEAT_INDEX 1
#define AFE_FUNCTIONALITY_REGULATOR_CP_HUMIDITY 2
#define AFE_FUNCTIONALITY_REGULATOR_CP_ABSOLOUTE_HUMIDITY 3
#define AFE_FUNCTIONALITY_REGULATOR_CP_DEW_POINT 4
#endif // AFE_CONFIG_HARDWARE_DHT
#endif // AFE_CONFIG_FUNCTIONALITY_REGULATOR

/* Relay thermal protection */
#ifdef AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_FUNCTIONALITY_THERMAL_PROTECTOR_DEFAULT_ENABLED true
#define AFE_FUNCTIONALITY_THERMAL_PROTECTOR_DEFAULT_TEMPERATURE 0
#define AFE_CONFIG_API_JSON_THERMAL_PROTECTOR_DATA_LENGTH 18   // {"enabled":false}
#endif // AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR

/* Config sites IDs */
#define AFE_CONFIG_SITE_INDEX 0
#define AFE_CONFIG_SITE_DEVICE 1
#define AFE_CONFIG_SITE_NETWORK 2
#define AFE_CONFIG_SITE_MQTT 3
#define AFE_CONFIG_SITE_MQTT_TOPICS 4
#define AFE_CONFIG_SITE_DOMOTICZ 5
#define AFE_CONFIG_SITE_LED 6
#define AFE_CONFIG_SITE_SYSTEM_LED 7
#define AFE_CONFIG_SITE_RELAY 8
#define AFE_CONFIG_SITE_SWITCH 9
#define AFE_CONFIG_SITE_PASSWORD 10
#define AFE_CONFIG_SITE_PRO_VERSION 11
#define AFE_CONFIG_SITE_ANALOG_INPUT 12
#define AFE_CONFIG_SITE_CONTACTRON 13
#define AFE_CONFIG_SITE_GATE 14
#define AFE_CONFIG_SITE_EXIT 15
#define AFE_CONFIG_SITE_RESET 16
#define AFE_CONFIG_SITE_POST_RESET 17
#define AFE_CONFIG_SITE_FIRST_TIME 18
#define AFE_CONFIG_SITE_FIRST_TIME_CONNECTING 19
#define AFE_CONFIG_SITE_UPGRADE 20
#define AFE_CONFIG_SITE_POST_UPGRADE 21
#define AFE_CONFIG_SITE_UART 22
#define AFE_CONFIG_SITE_HPMA115S0 23
#define AFE_CONFIG_SITE_BMEX80 24
#define AFE_CONFIG_SITE_BH1750 25
#define AFE_CONFIG_SITE_AS3935 26
#define AFE_CONFIG_SITE_I2C 27
#define AFE_CONFIG_SITE_DS18B20 28
#define AFE_CONFIG_SITE_ANEMOMETER_SENSOR 29
#define AFE_CONFIG_SITE_RAINMETER_SENSOR 30
#define AFE_CONFIG_SITE_REGULATOR 31
#define AFE_CONFIG_SITE_THERMAL_PROTECTOR 32
#define AFE_CONFIG_SITE_DHT 33
#define AFE_CONFIG_SITE_BINARY_SENSOR 34



/* ***************** APIs: Config and defaults *********************/

#ifdef AFE_CONFIG_HARDWARE_RELAY
#define AFE_CONFIG_HARDWARE_RELAY_DEFAULT_STATE_MQTT_CONNECTED                 \
  0    // Default State of relay after connection to MQTT Broker is established.
#endif // AFE_CONFIG_HARDWARE_RELAY

/* Configs releated to Domoticz APIs */
#ifdef AFE_CONFIG_API_DOMOTICZ_ENABLED
#define AFE_DOMOTICZ_VERSION_0 0 // 4.10x
#define AFE_DOMOTICZ_VERSION_1 1 // 2020.x
#define AFE_DOMOTICZ_VERSION_DEFAULT AFE_DOMOTICZ_VERSION_0
#define AFE_DOMOTICZ_IDX_NOT_PROCESSED 0
#define AFE_DOMOTICZ_DEFAULT_IDX 0 // Default value for IDX
#define AFE_DOMOTICZ_IDX_MIN_FORM_DEFAULT "0"
#define AFE_DOMOTICZ_IDX_MAX_FORM_DEFAULT "999999"
#define AFE_CONFIG_API_HTTP_TIMEOUT  200 // Time for HTTP response. If 5000 than device goes to config mode if
      // Domoticz is Off, button is pressed and HTTP Domoticz API is on
#define AFE_FIRMARE_API AFE_API_DOMOTICZ // Type of the firmware API: DOMOTICZ
#define AFE_CONFIG_API_DOMOTICZ_TOPIC_IN "domoticz/in" // MQTT Topic for outgoing from AFE messages
#define AFE_CONFIG_API_DOMOTICZ_TOPIC_OUT "domoticz/out" // MQTT Topic Domoticz uses for publishing messages
#define AFE_CONFIG_API_JSON_BUFFER_SIZE  380 // Size of the incoming Domoticz MQTT Messages. It may be to small for
      // messages that contains description
#define AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH 57 // Outgoing MQTT message size for switch
#define AFE_CONFIG_API_JSON_DEVICE_COMMAND_LENGTH 70 // Outgoing MQTT message size for custom sensor

#ifdef AFE_CONFIG_HARDWARE_GATE
#define AFE_CONFIG_API_JSON_GATE_COMMAND_LENGTH AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH
#endif // AFE_CONFIG_HARDWARE_GATE

#ifdef AFE_CONFIG_HARDWARE_CONTACTRON
#define AFE_CONFIG_API_JSON_CONTACTRON_COMMAND_LENGTH AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH
#endif // AFE_CONFIG_HARDWARE_CONTACTRON

#ifdef AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR
#define AFE_CONFIG_API_JSON_ANEMOMETER_COMMAND_LENGTH 100 // @TODO to check
#endif // AFE_CONFIG_HARDWARE_ANEMOMETER_SENSOR

#ifdef AFE_CONFIG_HARDWARE_RAINMETER_SENSOR
#define AFE_CONFIG_API_JSON_RAINMETER_COMMAND_LENGTH 100 // @TODO to check
#endif // AFE_CONFIG_HARDWARE_RAINMETER_SENSOR

#ifdef AFE_CONFIG_FUNCTIONALITY_BATTERYMETER
#define AFE_CONFIG_API_JSON_BATTERYMETER_COMMAND_LENGTH 100 // @TODO to check
#endif // AFE_CONFIG_FUNCTIONALITY_BATTERYMETER

#ifdef AFE_CONFIG_FUNCTIONALITY_REGULATOR
#define AFE_CONFIG_API_JSON_REGULATOR_COMMAND_LENGTH AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH // it's a switch
#endif // AFE_CONFIG_FUNCTIONALITY_REGULATOR

#ifdef AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR
#define AFE_CONFIG_API_JSON_THERMAL_PROTECTOR_COMMAND_LENGTH AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH // it's a switch
#endif // AFE_CONFIG_FUNCTIONALITY_THERMAL_PROTECTOR

#ifdef AFE_CONFIG_HARDWARE_DS18B20
#define AFE_CONFIG_API_JSON_DS18B20_COMMAND_LENGTH 66
#endif

#ifdef AFE_CONFIG_HARDWARE_DHT
#define AFE_CONFIG_API_JSON_DHT_COMMAND_LENGTH 200
#endif

#ifdef AFE_CONFIG_HARDWARE_BINARY_SENSOR
#define AFE_CONFIG_API_JSON_BINARY_SENSOR_COMMAND_LENGTH AFE_CONFIG_API_JSON_SWITCH_COMMAND_LENGTH
#endif 


#define AFE_CONFIG_API_DOMOTICZ_URL_LENGTH  190 // Outgoing url size for statuses updates to Domoticz

#ifdef AFE_CONFIG_HUMIDITY
/* Humidity Domoticz state*/
typedef enum {
  AFE_HUMIDITY_NORMAL = 0,
  AFE_HUMIDITY_COMFORTABLE = 1,
  AFE_HUMIDITY_DRY = 2,
  AFE_HUMIDITY_WET = 3,
} afe_humidity_domoticz_state_t;
#endif

#else // Defauals for None-Domoticz MQTT

#define AFE_FIRMARE_API AFE_API_STANDARD // Type of the firmware API: STANDRARD
#define AFE_CONFIG_MQTT_TOPIC_CMD_LENGTH 69 // Size of a Command topic: MQTT_BASIC_CONFIG + 4
#define AFE_CONFIG_MQTT_TOPIC_STATE_LENGTH 71 // Size of a State topic: MQTT_BASIC_CONFIG + 6
 

#endif // AFE_CONFIG_API_DOMOTICZ_ENABLED

/* Defaults for each MQTT Version (standard and domoticz) */
#define AFE_CONFIG_MQTT_DEFAULT_TIMEOUT  5000 // Timeout to shorten wait time, useful to have it low if MQTT server is down
#define AFE_CONFIG_MQTT_DEFAULT_PORT 1883 // Default MQTT Broker port
#define AFE_CONFIG_MQTT_DEFAULT_BUFFER_SIZE 1195 //768 // Default MQTT Buffer size - must handle entire message, max JSON is BME680, AFE_CONFIG_API_JSON_BMEX80_DATA_LENGTH
#define AFE_CONFIG_FUNCTIONALITY_MQTT_LWT
#define AFE_CONFIG_MQTT_DEFAULT_RETAIN_LWT false
#define AFE_CONFIG_MQTT_DEFAULT_RETAIN_ALL false
#define AFE_CONFIG_MQTT_DEFAULT_HOST_PING_BEFORE_CONNECTION false
#define AFE_CONFIG_MQTT_DEFAULT_HOST_PINGS_NUMBER 1
#define AFE_CONFIG_MQTT_DEFAULT_HOST_PINGS_TIMEOUT 1000 // ms

/* ***************** Files: Config and defaults *********************/

/* Configuration files names */
#define AFE_FILE_DOMOTICZ_CONFIGURATION "cfg-domoticz-server.json"
#define AFE_FILE_DEVICE_UID "cfg-device-uid.json"
#define AFE_FILE_MQTT_BROKER_CONFIGURATION "cfg-mqtt-broker.json"
#define AFE_FILE_DEVICE_MODE "cfg-device-mode.json"
#define AFE_FILE_PRO_VERSION_CONFIGURATION "cfg-pro-version.json"
#define AFE_FILE_PASSWORD_CONFIGURATION "cfg-password.json"
#define AFE_FILE_DEVICE_CONFIGURATION "cfg-device.json"
#define AFE_FILE_FIRMWARE_CONFIGURATION "cfg-firmware.json"
#define AFE_FILE_NETWORK_CONFIGURATION "cfg-network.json"
#define AFE_FILE_I2C_CONFIGURATION "cfg-i2c.json"
#define AFE_FILE_LED_CONFIGURATION "cfg-led-%d.json"
#define AFE_FILE_SYSTEM_LED_CONFIGURATION "cfg-system-led.json"
#define AFE_FILE_RELAY_CONFIGURATION "cfg-relay-%d.json"
#define AFE_FILE_RELAY_STATE_CONFIGURATION "cfg-relay-state-%d.json"
#define AFE_FILE_SWITCH_CONFIGURATION "cfg-switch-%d.json"
#define AFE_FILE_ADC_CONFIGURATION "cfg-analog-input.json"
#define AFE_FILE_UART_CONFIGURATION "cfg-uart.json"
#define AFE_FILE_ANEMOMETER_SENSOR_CONFIGURATION "cfg-anemometer-sensor-0.json"
#define AFE_FILE_RAINMETER_SENSOR_CONFIGURATION "cfg-rainmeter-sensor-0.json"
#define AFE_FILE_RAINMETER_SENSOR_DATA "/cfg-rainmeter-data-0.json"
#define AFE_FILE_REGULATOR_CONFIGURATION "/cfg-regulator-%d.json"
#define AFE_FILE_THERMAL_PROTECTOR_CONFIGURATION "/cfg-theremal-protector-%d.json"
#define AFE_FILE_DS18B20_SENSOR_CONFIGURATION "/cfg-ds18b20-%d.json"
#define AFE_FILE_CONTACTRON_CONFIGURATION "cfg-contactron-%d.json"
#define AFE_FILE_GATE_CONFIGURATION "cfg-gate-%d.json"
#define AFE_FILE_GATE_STATE_CONFIGURATION "cfg-gate-state-%d.json"
#define AFE_FILE_HPMA114S0_CONFIGURATION "cfg-hpma115s0-%d.json"
#define AFE_FILE_BMX680_CONFIGURATION "cfg-BMEX80-%d.json"
#define AFE_FILE_BH1750_CONFIGURATION "cfg-bh1750-%d.json"
#define AFE_FILE_AS3935_CONFIGURATION "cfg-as3935-%d.json"
#define AFE_FILE_DHT_SENSOR_CONFIGURATION "/cfg-dht-%d.json"
#define AFE_FILE_BINARY_SENSOR_CONFIGURATION "/cfg-binary-sensor-%d.json"

/* Configuration files, JSON Buffers.  */
#define AFE_CONFIG_FILE_BUFFER_DEVICE_UID 46 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_MQTT_BROKER 352                                     // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_BH1750 221 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_I2C 54     // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_DEVICE_MODE 31 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_PRO_VERSION 78                                        // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_PASSWORD 72  // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_DEVICE 405   // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_FIRMWARE 145 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_NETWORK 375  // Verfied by ArduinoJson Assistant
#ifdef AFE_CONFIG_HARDWARE_MCP23017
#define AFE_CONFIG_FILE_BUFFER_LED 124 //  Verfied by ArduinoJson Assistant
#else
#define AFE_CONFIG_FILE_BUFFER_LED 76        // Verfied by ArduinoJson Assistant
#endif                                       // AFE_CONFIG_HARDWARE_MCP23017
#define AFE_CONFIG_FILE_BUFFER_SYSTEM_LED 30 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_RELAY  287 // Verfied by ArduinoJson Assistant for T6 only
#define AFE_CONFIG_FILE_BUFFER_RELAY_STATE  36 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_SWITCH  238 // Verfied by ArduinoJson Assistant for T6 only
#define AFE_CONFIG_FILE_BUFFER_ADC 489       // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_HPMA115S0 202 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_UART 54       // Verfied by ArduinoJson Assistant
#ifdef AFE_CONFIG_API_DOMOTICZ_ENABLED
#define AFE_CONFIG_FILE_BUFFER_BMEX80 984 // Verfied by ArduinoJson Assistant
#else
#define AFE_CONFIG_FILE_BUFFER_BMEX80 572 // Verfied by ArduinoJson Assistant
#endif
#define AFE_CONFIG_FILE_BUFFER_AS3935 439 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_CONTACTRON  241                                   // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_GATE 319 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_GATE_STATE 32
#define AFE_CONFIG_FILE_BUFFER_RAINMETER_SENSOR_DATA 1100 // Not verfied
#define AFE_CONFIG_FILE_BUFFER_DS18B20 407   // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_REGULATOR 337 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_THERMAL_PROTECTOR 261                                  // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_DHT 643 // Verfied by ArduinoJson Assistant
#define AFE_CONFIG_FILE_BUFFER_BINARY_SENSOR 238 // Verfied by ArduinoJson Assistant for T6 only

/* Form constants */
#define AFE_FORM_ITEM_TYPE_NUMBER "number"
#define AFE_FORM_ITEM_TYPE_TEXT "text"
#define AFE_FORM_ITEM_TYPE_PASSWORD "password"
#define AFE_FORM_ITEM_SKIP_PROPERTY "?"

#endif // _AFE_Configuration_h
