#ifndef _AFE_Hardware_HPMA115S0_h
#define _AFE_Hardware_HPMA115S0_h

#ifndef AFE_CONFIG_HARDWARE_UART
#define AFE_CONFIG_HARDWARE_UART
#endif

#ifndef AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#define AFE_CONFIG_DOMOTICZ_CUSTOME_SENSOR
#endif

#define HPMA115S0_TYPE_PM25 0
#define HPMA115S0_TYPE_PM10 1

#endif // _AFE_Hardware_HPMA115S0_h