#ifndef _AFE_Hardware_Binary_Sensor_h
#define _AFE_Hardware_Binary_Sensor_h

#define AFE_BINARY_SENSOR_OPEN 1
#define AFE_BINARY_SENSOR_CLOSED 0 
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_BOUNCING 10
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_REVERT_SIGNAL false
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_SENT_AS_SWITCH false
#define AFE_HARDWARE_BINARY_SENSOR_DEFAULT_INTERNAL_PULLUP_RESISTOR true
#define AFE_CONFIG_API_JSON_BINARY_SENSOR_DATA_LENGTH 19 // {"state":"closed"}

#endif // _AFE_Hardware_Binary_Sensor_h